const bcrypt = require('bcryptjs');

const ADMIN_USER = {
  email: 'admin@twostep.com',
  password: 'admin123',
  firstName: 'Admin',
  lastName: 'User',
  phone: '+8801407587330',
  role: 'admin',
};

const CATEGORIES = [
  { name: 'Men', slug: 'men', description: 'Men\'s athletic apparel and footwear', imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80', sortOrder: 1 },
  { name: 'Women', slug: 'women', description: 'Women\'s athletic apparel and footwear', imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800&q=80', sortOrder: 2 },
  { name: 'Kids', slug: 'kids', description: 'Kids\' athletic apparel and footwear', imageUrl: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&q=80', sortOrder: 3 },
  { name: 'Sports', slug: 'sports', description: 'Performance gear for every sport', imageUrl: 'https://images.unsplash.com/photo-1461896836934-bd45ea8e2843?w=800&q=80', sortOrder: 4 },
  { name: 'Sale', slug: 'sale', description: 'Special offers and discounts', imageUrl: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80', sortOrder: 5 },
];

const SUBCATEGORIES = [
  { name: 'Shoes', slug: 'shoes', parentSlug: null },
  { name: 'Clothing', slug: 'clothing', parentSlug: null },
  { name: 'Accessories', slug: 'accessories', parentSlug: null },
];

const PRODUCTS = [
  // ── MEN (6 products) ──
  {
    name: 'Velocity Running Shoes',
    description: 'Lightweight running shoes with responsive cushioning and breathable mesh upper. Designed for speed and comfort on every run.',
    price: 9899,
    salePrice: null,
    sku: 'MEN-SHOE-001',
    stockQuantity: 50,
    isFeatured: true,
    categorySlug: 'men',
    images: [
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80', alt: 'Velocity Running Shoes front view', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80', alt: 'Velocity Running Shoes side view' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80', alt: 'Velocity Running Shoes detail' },
    ],
    filters: [
      { key: 'size', value: '8' }, { key: 'size', value: '9' }, { key: 'size', value: '10' }, { key: 'size', value: '11' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Red' },
    ],
  },
  {
    name: 'Athletic Performance Tee',
    description: 'Moisture-wicking performance t-shirt with anti-odor technology. Perfect for intense training sessions.',
    price: 3849,
    salePrice: null,
    sku: 'MEN-TOP-001',
    stockQuantity: 80,
    isFeatured: true,
    categorySlug: 'men',
    images: [
      { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80', alt: 'Athletic Performance Tee front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80', alt: 'Athletic Performance Tee detail' },
      { url: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&q=80', alt: 'Athletic Performance Tee back' },
    ],
    filters: [
      { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' }, { key: 'size', value: 'XL' },
      { key: 'color', value: 'White' }, { key: 'color', value: 'Black' }, { key: 'color', value: 'Navy' },
    ],
  },
  {
    name: 'Sport Crossbody Bag',
    description: 'Compact crossbody bag with water-resistant coating. Multiple compartments for organized storage during workouts.',
    price: 3299,
    salePrice: 2749,
    sku: 'MEN-ACC-001',
    stockQuantity: 40,
    isFeatured: false,
    categorySlug: 'men',
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80', alt: 'Sport Crossbody Bag', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=800&q=80', alt: 'Sport Crossbody Bag detail' },
      { url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80', alt: 'Sport Crossbody Bag side' },
    ],
    filters: [
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Gray' },
    ],
  },
  {
    name: 'Training Shorts',
    description: 'Flex lightweight training shorts with inner compression liner. Quick-dry fabric keeps you cool during workouts.',
    price: 3079,
    salePrice: null,
    sku: 'MEN-BOT-001',
    stockQuantity: 60,
    isFeatured: true,
    categorySlug: 'men',
    images: [
      { url: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80', alt: 'Training Shorts front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&q=80', alt: 'Training Shorts detail' },
      { url: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80', alt: 'Training Shorts back' },
    ],
    filters: [
      { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' }, { key: 'size', value: 'XL' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Gray' },
    ],
  },
  {
    name: 'Runner Jacket',
    description: 'Water-resistant running jacket with reflective details. Lightweight and packable for all-weather training.',
    price: 8799,
    salePrice: null,
    sku: 'MEN-OUT-001',
    stockQuantity: 35,
    isFeatured: true,
    categorySlug: 'men',
    images: [
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80', alt: 'Runner Jacket front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80', alt: 'Runner Jacket detail' },
      { url: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80', alt: 'Runner Jacket back' },
    ],
    filters: [
      { key: 'size', value: 'M' }, { key: 'size', value: 'L' }, { key: 'size', value: 'XL' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Navy' },
    ],
  },
  {
    name: 'Performance Socks 3-Pack',
    description: 'Cushioned performance socks with arch support and moisture management. Pack of 3 pairs.',
    price: 1649,
    salePrice: null,
    sku: 'MEN-ACC-002',
    stockQuantity: 100,
    isFeatured: false,
    categorySlug: 'men',
    images: [
      { url: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c87?w=800&q=80', alt: 'Performance Socks pack', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=800&q=80', alt: 'Performance Socks detail' },
      { url: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c87?w=800&q=80', alt: 'Performance Socks flat lay' },
    ],
    filters: [
      { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' },
      { key: 'color', value: 'White' }, { key: 'color', value: 'Black' },
    ],
  },

  // ── WOMEN (6 products) ──
  {
    name: 'Flex Training Shoes',
    description: 'Women\'s training shoes with flexible sole and supportive fit. Ideal for gym workouts and cross-training.',
    price: 9349,
    salePrice: null,
    sku: 'WOM-SHOE-001',
    stockQuantity: 45,
    isFeatured: true,
    categorySlug: 'women',
    images: [
      { url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&q=80', alt: 'Flex Training Shoes front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=800&q=80', alt: 'Flex Training Shoes side' },
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80', alt: 'Flex Training Shoes detail' },
    ],
    filters: [
      { key: 'size', value: '6' }, { key: 'size', value: '7' }, { key: 'size', value: '8' }, { key: 'size', value: '9' },
      { key: 'color', value: 'Pink' }, { key: 'color', value: 'White' },
    ],
  },
  {
    name: 'Sport Bra Elite',
    description: 'High-support sports bra with adjustable straps and moisture-wicking fabric. Maximum comfort during high-intensity workouts.',
    price: 4399,
    salePrice: null,
    sku: 'WOM-TOP-001',
    stockQuantity: 70,
    isFeatured: true,
    categorySlug: 'women',
    images: [
      { url: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800&q=80', alt: 'Sport Bra Elite front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1571513722275-4b419cb0c3e9?w=800&q=80', alt: 'Sport Bra Elite detail' },
      { url: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=800&q=80', alt: 'Sport Bra Elite back' },
    ],
    filters: [
      { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Pink' }, { key: 'color', value: 'White' },
    ],
  },
  {
    name: 'Gym Duffel Bag',
    description: 'Spacious gym duffel with shoe compartment and wet pocket. Durable water-resistant material.',
    price: 3849,
    salePrice: 3299,
    sku: 'WOM-ACC-001',
    stockQuantity: 30,
    isFeatured: false,
    categorySlug: 'women',
    images: [
      { url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80', alt: 'Gym Duffel Bag', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80', alt: 'Gym Duffel Bag detail' },
      { url: 'https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=800&q=80', alt: 'Gym Duffel Bag open' },
    ],
    filters: [
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Rose Gold' },
    ],
  },
  {
    name: 'Yoga Leggings',
    description: 'High-waist yoga leggings with 4-way stretch and hidden pocket. Buttery-soft fabric for ultimate comfort.',
    price: 5499,
    salePrice: null,
    sku: 'WOM-BOT-001',
    stockQuantity: 65,
    isFeatured: true,
    categorySlug: 'women',
    images: [
      { url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80', alt: 'Yoga Leggings front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80', alt: 'Yoga Leggings side' },
      { url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&q=80', alt: 'Yoga Leggings detail' },
    ],
    filters: [
      { key: 'size', value: 'XS' }, { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Navy' },
    ],
  },
  {
    name: 'Windbreaker Hoodie',
    description: 'Lightweight windbreaker hoodie with adjustable hood and zippered pockets. Perfect for outdoor training.',
    price: 7699,
    salePrice: null,
    sku: 'WOM-OUT-001',
    stockQuantity: 40,
    isFeatured: true,
    categorySlug: 'women',
    images: [
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80', alt: 'Windbreaker Hoodie front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80', alt: 'Windbreaker Hoodie detail' },
      { url: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80', alt: 'Windbreaker Hoodie back' },
    ],
    filters: [
      { key: 'size', value: 'XS' }, { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' },
      { key: 'color', value: 'Pink' }, { key: 'color', value: 'Black' },
    ],
  },
  {
    name: 'Headband Sport',
    description: 'Sweat-wicking sport headband with non-slip grip. Keeps hair and sweat out of your eyes during workouts.',
    price: 1429,
    salePrice: null,
    sku: 'WOM-ACC-002',
    stockQuantity: 90,
    isFeatured: false,
    categorySlug: 'women',
    images: [
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80', alt: 'Headband Sport', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80', alt: 'Headband Sport detail' },
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80', alt: 'Headband Sport flat lay' },
    ],
    filters: [
      { key: 'color', value: 'Black' }, { key: 'color', value: 'White' }, { key: 'color', value: 'Pink' },
    ],
  },

  // ── KIDS (6 products) ──
  {
    name: 'Kids Runner Shoes',
    description: 'Durable kids\' running shoes with easy slip-on design and cushioned sole. Built for active kids.',
    price: 4949,
    salePrice: null,
    sku: 'KID-SHOE-001',
    stockQuantity: 55,
    isFeatured: true,
    categorySlug: 'kids',
    images: [
      { url: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&q=80', alt: 'Kids Runner Shoes front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&q=80', alt: 'Kids Runner Shoes side' },
      { url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80', alt: 'Kids Runner Shoes detail' },
    ],
    filters: [
      { key: 'size', value: '1' }, { key: 'size', value: '2' }, { key: 'size', value: '3' }, { key: 'size', value: '4' },
      { key: 'color', value: 'Blue' }, { key: 'color', value: 'Red' },
    ],
  },
  {
    name: 'Kids Sport Tee',
    description: 'Fun and colorful kids\' sport tee with breathable fabric. Perfect for play and sports.',
    price: 2199,
    salePrice: null,
    sku: 'KID-TOP-001',
    stockQuantity: 75,
    isFeatured: false,
    categorySlug: 'kids',
    images: [
      { url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80', alt: 'Kids Sport Tee front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&q=80', alt: 'Kids Sport Tee detail' },
      { url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80', alt: 'Kids Sport Tee back' },
    ],
    filters: [
      { key: 'size', value: '4' }, { key: 'size', value: '6' }, { key: 'size', value: '8' }, { key: 'size', value: '10' },
      { key: 'color', value: 'Blue' }, { key: 'color', value: 'Green' },
    ],
  },
  {
    name: 'Kids Water Bottle',
    description: 'BPA-free kids\' water bottle with fun design. Leak-proof and easy to carry.',
    price: 1099,
    salePrice: null,
    sku: 'KID-ACC-001',
    stockQuantity: 120,
    isFeatured: false,
    categorySlug: 'kids',
    images: [
      { url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80', alt: 'Kids Water Bottle', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80', alt: 'Kids Water Bottle detail' },
      { url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80', alt: 'Kids Water Bottle open' },
    ],
    filters: [
      { key: 'color', value: 'Blue' }, { key: 'color', value: 'Pink' },
    ],
  },
  {
    name: 'Kids Track Pants',
    description: 'Comfortable kids\' track pants with elastic waistband and cuffed ankles. Machine washable.',
    price: 2749,
    salePrice: null,
    sku: 'KID-BOT-001',
    stockQuantity: 60,
    isFeatured: false,
    categorySlug: 'kids',
    images: [
      { url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80', alt: 'Kids Track Pants front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&q=80', alt: 'Kids Track Pants detail' },
      { url: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80', alt: 'Kids Track Pants side' },
    ],
    filters: [
      { key: 'size', value: '4' }, { key: 'size', value: '6' }, { key: 'size', value: '8' }, { key: 'size', value: '10' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Gray' },
    ],
  },
  {
    name: 'Kids Windbreaker',
    description: 'Lightweight kids\' windbreaker with fun colors. Water-resistant and packable for adventures.',
    price: 4399,
    salePrice: 3849,
    sku: 'KID-OUT-001',
    stockQuantity: 35,
    isFeatured: true,
    categorySlug: 'kids',
    images: [
      { url: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80', alt: 'Kids Windbreaker front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80', alt: 'Kids Windbreaker detail' },
      { url: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80', alt: 'Kids Windbreaker back' },
    ],
    filters: [
      { key: 'size', value: '4' }, { key: 'size', value: '6' }, { key: 'size', value: '8' }, { key: 'size', value: '10' },
      { key: 'color', value: 'Red' }, { key: 'color', value: 'Blue' },
    ],
  },
  {
    name: 'Kids Wristband Set',
    description: 'Set of 3 colorful kids\' wristbands. Sweat-absorbing and stretchy for comfort.',
    price: 879,
    salePrice: null,
    sku: 'KID-ACC-002',
    stockQuantity: 150,
    isFeatured: false,
    categorySlug: 'kids',
    images: [
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80', alt: 'Kids Wristband Set', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80', alt: 'Kids Wristband Set detail' },
      { url: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80', alt: 'Kids Wristband Set flat lay' },
    ],
    filters: [
      { key: 'color', value: 'Multi' },
    ],
  },

  // ── SPORTS (6 products) ──
  {
    name: 'Pro Basketball Shoes',
    description: 'High-top basketball shoes with ankle support and responsive cushioning. Dominate the court.',
    price: 13199,
    salePrice: 10999,
    sku: 'SPT-SHOE-001',
    stockQuantity: 30,
    isFeatured: true,
    categorySlug: 'sports',
    images: [
      { url: 'https://images.unsplash.com/photo-1579338559194-a162d19bf842?w=800&q=80', alt: 'Pro Basketball Shoes front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80', alt: 'Pro Basketball Shoes side' },
      { url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80', alt: 'Pro Basketball Shoes detail' },
    ],
    filters: [
      { key: 'size', value: '9' }, { key: 'size', value: '10' }, { key: 'size', value: '11' }, { key: 'size', value: '12' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'White' },
    ],
  },
  {
    name: 'Compression Tank',
    description: 'Performance compression tank with muscle support and ventilation zones. Train harder, recover faster.',
    price: 4949,
    salePrice: null,
    sku: 'SPT-TOP-001',
    stockQuantity: 50,
    isFeatured: true,
    categorySlug: 'sports',
    images: [
      { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80', alt: 'Compression Tank front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80', alt: 'Compression Tank detail' },
      { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80', alt: 'Compression Tank back' },
    ],
    filters: [
      { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' }, { key: 'size', value: 'XL' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'White' },
    ],
  },
  {
    name: 'Gym Gloves',
    description: 'Padded gym gloves with wrist support and breathable mesh. Protect your hands during heavy lifts.',
    price: 2199,
    salePrice: null,
    sku: 'SPT-ACC-001',
    stockQuantity: 80,
    isFeatured: false,
    categorySlug: 'sports',
    images: [
      { url: 'https://images.unsplash.com/photo-1583473848882-f9a5bc374873?w=800&q=80', alt: 'Gym Gloves', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1583473848882-f9a5bc374873?w=800&q=80', alt: 'Gym Gloves detail' },
      { url: 'https://images.unsplash.com/photo-1583473848882-f9a5bc374873?w=800&q=80', alt: 'Gym Gloves open' },
    ],
    filters: [
      { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Red' },
    ],
  },
  {
    name: 'Marathon Shorts',
    description: 'Ultra-light marathon shorts with split hem for maximum stride. Built for long-distance performance.',
    price: 3629,
    salePrice: null,
    sku: 'SPT-BOT-001',
    stockQuantity: 45,
    isFeatured: false,
    categorySlug: 'sports',
    images: [
      { url: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80', alt: 'Marathon Shorts front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&q=80', alt: 'Marathon Shorts detail' },
      { url: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80', alt: 'Marathon Shorts side' },
    ],
    filters: [
      { key: 'size', value: 'S' }, { key: 'size', value: 'M' }, { key: 'size', value: 'L' }, { key: 'size', value: 'XL' },
      { key: 'color', value: 'Black' }, { key: 'color', value: 'Blue' },
    ],
  },
  {
    name: 'Trail Running Jacket',
    description: 'Waterproof trail running jacket with hood and ventilation zips. Conquer any weather on the trails.',
    price: 9899,
    salePrice: null,
    sku: 'SPT-OUT-001',
    stockQuantity: 25,
    isFeatured: true,
    categorySlug: 'sports',
    images: [
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=80', alt: 'Trail Running Jacket front', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80', alt: 'Trail Running Jacket detail' },
      { url: 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&q=80', alt: 'Trail Running Jacket back' },
    ],
    filters: [
      { key: 'size', value: 'M' }, { key: 'size', value: 'L' }, { key: 'size', value: 'XL' },
      { key: 'color', value: 'Green' }, { key: 'color', value: 'Black' },
    ],
  },
  {
    name: 'Sports Watch',
    description: 'Multi-function sports watch with heart rate monitor, GPS, and 7-day battery life. Track every move.',
    price: 6599,
    salePrice: 5499,
    sku: 'SPT-ACC-002',
    stockQuantity: 60,
    isFeatured: true,
    categorySlug: 'sports',
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80', alt: 'Sports Watch face', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80', alt: 'Sports Watch side' },
      { url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80', alt: 'Sports Watch detail' },
    ],
    filters: [
      { key: 'color', value: 'Black' }, { key: 'color', value: 'White' },
    ],
  },
];

module.exports = { ADMIN_USER, CATEGORIES, SUBCATEGORIES, PRODUCTS };
